const Constants = {
    tobeExcluded: [
        "signature",
        "signatureFirstName",
        "signatureLastName",
        "termsAgreement",
        "futureProjectsInterest",
        "identificationFile",
        "agreementConfirmation",
        "sdc_fname",
        "sdc_lname",
        "sdc_signature",
        "grd_sdc_fname",
        "grd_sdc_lname",
        "noAvailabilityReason",
        "registeredAs",
        "gender",
        "agreementConfirmation",
        "res_st",
        "source",
        "industries",
        "csadate",
        "grd_signatureFirstName",
        "grd_signatureLastName"
    ],
    savedIfYesOnly: [
        "interestedInRecruiting",
        "isMultipleEthnicities",
        "isPregnant",
        "onsiteAvailability"
    ],
    registeredAs: {
        0: 'I am registering as a participant over the age of 18',
        1: 'I am a parent or guardian registering a child under 18'
    },
    genders: {
        // Do no modify these in any case !!
        0: "Male",
        1: "Female",
        2: "Non-binary",
        3: "Prefer not to say'"
    },

    usStates: {
        // Do no modify these in any case !!
        0: '',
        1: 'Alabama',
        2: 'Alaska',
        3: 'Arizona',
        4: 'Arkansas',
        5: 'California',
        6: 'Colorado',
        7: 'Connecticut',
        8: 'Delaware',
        9: 'Florida',
        10: 'Georgia',
        11: 'Hawaii',
        12: 'Idaho',
        13: 'Illinois',
        14: 'Indiana',
        15: 'Iowa',
        16: 'Kansas',
        17: 'Kentucky',
        18: 'Louisiana',
        19: 'Maine',
        20: 'Maryland',
        21: 'Massachusetts',
        22: 'Michigan',
        23: 'Minnesota',
        24: 'Mississippi',
        25: 'Missouri',
        26: 'Montana',
        27: 'Nebraska',
        28: 'Nevada',
        29: 'New Hampshire',
        30: 'New Jersey',
        31: 'New Mexico',
        32: 'New York',
        33: 'North Carolina',
        34: 'North Dakota',
        35: 'Ohio',
        36: 'Oklahoma',
        37: 'Oregon',
        38: 'Pennsylvania',
        39: 'Rhode Island',
        40: 'South Carolina',
        41: 'South Dakota',
        42: 'Tennessee',
        43: 'Texas',
        44: 'Utah',
        45: 'Vermont',
        46: 'Virginia',
        47: 'Washington',
        48: 'Washington, D.C.',
        49: 'West Virginia',
        50: 'Wisconsin',
        51: 'Wyoming'
    },

    noAvailabilityReasons: {
        0: 'I am generally not interested in going to an onsite study.',
        1: "I am hesitant to join a study when I don't know what it is about but I would like to have more information.",
        2: 'I am not interested in participating in this study.',
        3: 'I am worried about sharing personal information.',
        4: 'I do not have time at the moment.',
        5: 'I do not want to answer this question.',
        6: 'Something else - please provide more information in the feedback if you want.',
        7: 'The compensation is generally not enough for me.',
        8: 'The compensation is not enough for me to go to Los Angeles. I would go if the place would be nearer.',
        9: 'The place is too far for me.'
    },

    otherCompanies: {
        0: 'Alphabet',
        1: 'Amazon',
        2: 'Appen',
        3: 'Apple',
        4: 'BOSE',
        5: 'Google',
        6: 'HTC',
        7: 'Huawei',
        8: 'IBM',
        9: 'LG',
        10: 'Magic Leap',
        11: 'Meta',
        12: 'Microsoft',
        13: 'Netflix',
        14: 'Nuance',
        15: 'Samsung',
        16: 'Sony',
        17: 'Yahoo'
    },
    industries: {
        0: 'Aerospace',
        1: 'Commercial Services',
        2: 'Health Care and Medicine',
        3: 'Public Services',
        4: 'Agriculture',
        5: 'Construction',
        6: 'Hospitality',
        7: 'Technology',
        8: 'Advertising',
        9: 'Education',
        10: 'Marketing and Media',
        11: 'Telecommunitacions',
        12: 'Fashion',
        13: 'Entertainment',
        14: 'Manufacturing',
        15: 'Tourism',
        16: 'Finance',
        17: 'Energy Sector',
        18: 'Mining',
        19: 'Transportation',
        20: 'Charity or NGO',
        21: 'Environmental Sciences',
        22: 'Pharmaceutics',
        23: 'I am currently not working',
    },

    sources: {
        0: 'Respondent',
        1: 'TELUS International Website',
        2: 'Facebook',
        3: 'LinkedIn',
        4: 'Flyer',
        5: 'Newspaper',
        6: 'I was referred by someone',
        7: 'Instagram',
        8: 'Indeed',
        9: 'FlexJobs',
        10: 'Work Market platform',
        11: 'Through my association',
        12: 'Twitter',
        13: 'Craiglist',
        14: 'Google Ad',
        15: "I'm a TELUS International employee",
        16: 'I was contacted by TELUS International directly',
        17: 'Snapchat',
        18: 'Reddit',
        19: 'Retirement Jobs',
        20: 'TikTok'
    },

    participantStatuses: {
        // Do no modify these in any case !!
        0: "",
        1: "Contacted",
        2: "Scheduled",
        3: "Completed",
        4: "Not Selected",
        5: "Rejected",
        6: "Duplicate",
        7: "Withdrawn"
    },
    ageRanges: [
        "<13",
        "13-14",
        "15-17",
        "18-20",
        "21-30",
        "31-40",
        "41-50",
        "51-60",
        "61-70",
        "71-75",
        "75+"
    ],

    getKeyByValue: function (obj, value) {
        return Object.keys(obj).find(key => obj[key] === value);
    }

}

export default Constants;